[package]
name = "tonk-client"
version = "0.0.0"
edition = "2021"
authors = ["Lila Pause"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
